---
- name: Mkdir for java installation
  file:
    path: '{{ java_path }}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 'Install java {{ java_full_version }}'
  unarchive:
    src: '{{ java_artifact }}'
    dest: '{{ java_path }}'
    remote_src: true
    owner: root
    group: root
    mode: 0755
    list_files: true
  register: unarchived_folder

- name: Set actual java directory
  set_fact:
    java_folder: '{{ unarchived_folder.files[0].split("/")[0] }}'
