---
- name: Check that the java_folder exists
  win_stat:
    path: '{{ java_path }}\{{ java_folder }}/bin'
  register: java_folder_bin

- name: debug path
  debug:
    var: java_folder_bin

- name: Install java from tarball
  block:
  - name: Mkdir for java installation
    win_file:
      path: '{{ java_path }}\{{ java_folder }}'
      state: directory

  - name: create temporary directory
    win_tempfile:
      state: directory
    register: temp_dir_path

  - name: debug temp_dir_path
    debug:
      var: temp_dir_path

  - name: Unzip java archive
    win_unzip:
      src: '{{ java_artifact }}'
      dest: '{{ temp_dir_path }}'

  - name: Find java_folder
    win_find:
      paths: '{{ temp_dir_path }}'
      recurse: false
      file_type: directory
      patterns: '*'
      use_regex: true
    register: java_temp_folder

  - name: debug java_temp_folder
    debug:
      var: java_temp_folder

  - name: Copy from temp
    win_copy:
      src: '{{ java_temp_folder.files | map(attribute="path") | list | last }}\'
      dest: '{{ java_path }}\{{ java_folder }}'
      remote_src: true
  when: not java_folder_bin.stat.exists
