---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
# platforms:
#   - name: "Test message"
#     debug:
#       msg: "TEST MESSAGE"
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
