---
- name: 'Fetch root page {{ sapjvm_root_page }}'
  win_uri:
    url: '{{ sapjvm_root_page }}'
    return_content: true
  register: root_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ root_page['content']
        | regex_findall('(additional/sapjvm-'
          + java_major_version|string
          + '[\d.]+-windows-x64.zip)')
      }}

- name: Set artifact basename
  set_fact:
    artifact_url: '{{ release_url[0] }}'
    artifact_basename: '{{ release_url[0].split("/")[-1] }}'

- name: Debug artifact_url
  debug:
    var: artifact_url

- name: Debug artifact_basename
  debug:
    var: artifact_basename

- name: Check artifact existence
  win_stat:
    path: '{{ download_path }}\{{ artifact_basename }}'
  register: artifact

- name: Debug artifact
  debug:
    var: artifact

- name: 'Download {{ artifact_basename }} artifact '
  win_get_url:
    url: '{{ sapjvm_root_page }}/{{ artifact_url }}'
    headers:
      Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt
    dest: '{{ download_path }}'
  register: file_downloaded
  when: not artifact.stat.exists
  retries: 20
  delay: 5
  until: file_downloaded is succeeded

- name: Debug file_downloaded
  debug:
    var: file_downloaded
