---
- name: Set BASE variables based on java distribution
  include_vars: '{{ distribution }}'
  with_first_found:
    - '{{ ansible_system }}/{{ java_distribution }}/base_vars.yml'
    - '{{ ansible_system }}/{{ java_distribution }}/default.yml'
  loop_control:
    loop_var: distribution

- name: 'Fetch oracle artifact with {{ transport }} transport'
  include_tasks: '{{ transport_driver }}'
  with_first_found:
    - 'fetch/{{ transport }}.yml'
    - fetch/unknown-transport.yml
  loop_control:
    loop_var: transport_driver

- name: Set PARSE variables based on java distribution
  include_vars:
    file: '{{ ansible_system }}/{{ java_distribution }}/parse_{{ java_binary_type }}.yml'
  when: java_binary_type != 'chocolatey'

- name: 'Perform {{ java_binary_type }} install'
  include_tasks: '{{ ansible_system }}/install/{{ java_binary_type }}.yml'

- name: Find java_folder
  win_find:
    paths: '{{ java_path }}'
    recurse: false
    file_type: directory
    patterns: '{{ java_folder }}'
    use_regex: true
  register: java_dir

- name: Debug java_dir in system
  debug:
    var: java_dir

- name: Set actual java directory
  set_fact:
    java_act_path: "{{ java_dir.files | map(attribute='path') | list | last }}"

- name: Debug java_act_path in system
  debug:
    var: java_act_path

- name: Set java environment variable
  win_environment:
    name: JAVA_HOME
    state: present
    value: '{{ java_act_path }}'
    level: machine

- name: Ensure that 'JAVA_HOME\bin' present in 'Path' variable
  win_path:
    elements: '{{ java_act_path }}\bin'
    state: present
    scope: machine
